import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ReduxProvider from "./redux/provider";
import { SocketProvider } from "@/hooks/useSocket";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Beach Bunny House",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="app-body" className={inter.className}>
        <ReduxProvider>
          <SocketProvider>
            <Navbar />
            {children}
            <Footer />
          </SocketProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
